apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
spec:
  replicas: {{ .Values.backend.profile.replicas }}
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: {{ .Values.backend.profile.image }}
          ports:
            - containerPort: {{ .Values.backend.profile.port }}
