apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: ClusterIP
  selector:
    app: hello-service
  ports:
    - port: {{ .Values.backend.hello.port }}
      targetPort: {{ .Values.backend.hello.port }}
